[package]
name = "evm"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[dependencies]
imgui = { version = "0.7.0", features = ["wasm"] }
nom = "7.0.0"
path-clean = "0.1.0"
# winit = {version =  "0.25.0" , features = ["stdweb", "wasm-bindgen"] }
glow = "0.11.0"
web-sys = { version = "0.3", features=["HtmlCanvasElement", "WebGl2RenderingContext", "Window"] }
wasm-bindgen = { version = "0.2" }



[lib]
crate-type = ["cdylib", "rlib"]